/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'scnqzh' at '11/13/15 4:03 PM' with Gradle 2.6
 *
 * @author scnqzh, @date 11/13/15 4:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
